# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yLHuitjliO1ywdJVpbaYD09dT8etGVhZ
"""

import os
import joblib
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

# Create FastAPI app
app = FastAPI(title="Text Classifier API", version="1.0")

# Load model
MODEL_PATH = os.getenv("MODEL_PATH", "model.joblib")

try:
    model = joblib.load(MODEL_PATH)
except Exception as e:
    raise RuntimeError(f"Error loading model: {e}")

# Request format
class PredictRequest(BaseModel):
    text: str = Field(..., min_length=1)

# Health check
@app.get("/")
def health():
    return {"status": "ok"}

# Prediction endpoint
@app.post("/predict")
def predict(req: PredictRequest):
    try:
        pred = model.predict([req.text])[0]

        probs = None
        if hasattr(model, "predict_proba"):
            p = model.predict_proba([req.text])[0]
            probs = {str(i): float(v) for i, v in enumerate(p)}

        return {
            "prediction": str(pred),
            "probabilities": probs
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))